/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.edu.nuce.daotao.StoreManager.view.jpanel;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import lombok.extern.log4j.Log4j2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import vn.edu.nuce.daotao.StoreManager.controller.BillController;
import vn.edu.nuce.daotao.StoreManager.controller.ProductController;
import vn.edu.nuce.daotao.StoreManager.controller.ProductTypeController;
import vn.edu.nuce.daotao.StoreManager.controller.ReceiptController;
import vn.edu.nuce.daotao.StoreManager.response.procedure.ProcedureReportBill;
import vn.edu.nuce.daotao.StoreManager.response.procedure.ProcedureReportProduct;
import vn.edu.nuce.daotao.StoreManager.response.procedure.ProcedureReportProductInventory;
import vn.edu.nuce.daotao.StoreManager.service.impl.WriteReportBill;
import vn.edu.nuce.daotao.StoreManager.service.impl.WriteReportProduct;
import vn.edu.nuce.daotao.StoreManager.service.impl.WriteReportProductInventory;
import vn.edu.nuce.daotao.StoreManager.service.impl.WriteReportReceipt;
import vn.edu.nuce.daotao.StoreManager.validator.CodeSystem;

/**
 *
 * @author Anh
 */
@Component
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
@Log4j2
public class ReportJpanel extends javax.swing.JPanel implements CommonJpanel {

    @Autowired
    private BillController billController;

    @Autowired
    private ReceiptController receiptController;

    @Autowired
    private ProductController productController;

    int count = 0;
    int indexItem = 0;
    /**
     * 0 = default 1 = update 2 = add 3 = edit 4 = delete 5 = search 6 = cancel
     */
    static int checkButton = 0;
    List<Object[]> customerResponses;
    DefaultTableModel tableModel;
    TableRowSorter<TableModel> tableRowSorter;

    //position
    int countProductType = 0;
    int indexItemProductType = 0;
    /**
     * 0 = default 1 = update 2 = add 3 = edit 4 = delete 5 = search 6 = cancel
     */
    static int checkButtonProductType = 0;
    List<Object[]> productTypeResponses;
    DefaultTableModel tableModelProductType;
    TableRowSorter<TableModel> tableRowSorterProductType;

    static int checkButton_receipt = 0;
    List<Object[]> customerResponsesReceipt;
    DefaultTableModel tableModelReceipt;
    TableRowSorter<TableModel> tableRowSorterReceipt;

    List<Object[]> productTypeResponsesReceipt;
    DefaultTableModel tableModelProductTypeReceipt;
    TableRowSorter<TableModel> tableRowSorterProductTypeReceipt;

    List<Object[]> customerResponsesProduct;
    List<Object[]> customerResponsesProductInventory;

    DefaultTableModel tableModelProduct;
    DefaultTableModel tableModelProductInventory;

    public ReportJpanel() {
        initComponents();
    }

    public void init() {
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtCodeBill = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtFromDate = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        txtEnđate = new javax.swing.JFormattedTextField();
        txtCusName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtStaffName = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtQttyBill = new javax.swing.JTextField();
        txtDCashBill = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblBillReport = new javax.swing.JTable();
        jPanel32 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtRecieptCode = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtFromDateReceipt = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        txtEndDateReceipt = new javax.swing.JFormattedTextField();
        txtDistributorName = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtStaffNameReceipt = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txtQttyBillReceipt = new javax.swing.JTextField();
        txtDCashReceipt = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblReceipt = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtFromDateProduct = new javax.swing.JFormattedTextField();
        jLabel34 = new javax.swing.JLabel();
        txtEndDateProduct = new javax.swing.JFormattedTextField();
        cbbType = new javax.swing.JComboBox<>();
        jPanel26 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txtQttyProduct = new javax.swing.JTextField();
        txtDCashProduct = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        btnFillProduct = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();

        jTabbedPane1.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N

        jPanel18.setLayout(new java.awt.GridLayout(1, 0));

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        jLabel17.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel17.setText("Từ ngày");

        txtCodeBill.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel18.setText("Mã hóa đơn");

        txtFromDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel19.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel19.setText("Đến ngày");

        txtEnđate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        txtCusName.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel20.setText("Tên khách hàng");

        jLabel24.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel24.setText("Tên nhân viên");

        txtStaffName.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEnđate, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFromDate))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodeBill)
                            .addComponent(txtCusName)
                            .addComponent(txtStaffName)))))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodeBill, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEnđate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.add(jPanel20);

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder("Tổng hợp"));

        jLabel21.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel21.setText("Số lượng");

        txtQttyBill.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtQttyBill.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtDCashBill.setFont(new java.awt.Font("Cambria", 1, 27)); // NOI18N
        txtDCashBill.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel22.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel22.setText("Tổng tiền");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQttyBill, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(txtDCashBill)))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQttyBill, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDCashBill))
                .addContainerGap())
        );

        jPanel18.add(jPanel22);
        jPanel22.getAccessibleContext().setAccessibleName("Thống kê");

        jButton2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selection.png"))); // NOI18N
        jButton1.setText("Lọc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        jButton3.setText("Xuất ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        tblBillReport.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblBillReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBillReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBillReportMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblBillReport);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hóa đơn", new javax.swing.ImageIcon(getClass().getResource("/images/waiter (2).png")), jPanel1); // NOI18N

        jPanel32.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N

        jPanel19.setLayout(new java.awt.GridLayout(1, 0));

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        jLabel25.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel25.setText("Từ ngày");

        txtRecieptCode.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel26.setText("Mã phiếu nhập");

        txtFromDateReceipt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel27.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel27.setText("Đến ngày");

        txtEndDateReceipt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        txtDistributorName.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel28.setText("Tên nhà phân phối");

        jLabel29.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel29.setText("Tên nhân viên");

        txtStaffNameReceipt.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFromDateReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(txtRecieptCode)
                    .addComponent(txtDistributorName)
                    .addComponent(txtStaffNameReceipt)
                    .addComponent(txtEndDateReceipt, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRecieptCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDistributorName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStaffNameReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFromDateReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEndDateReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.add(jPanel21);

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder("Tổng hợp"));

        jLabel30.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel30.setText("Số lượng");

        txtQttyBillReceipt.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtQttyBillReceipt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtDCashReceipt.setFont(new java.awt.Font("Cambria", 1, 27)); // NOI18N
        txtDCashReceipt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel31.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel31.setText("Tổng tiền");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQttyBillReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(txtDCashReceipt)))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQttyBillReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDCashReceipt))
                .addContainerGap())
        );

        jPanel19.add(jPanel23);

        jButton4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);

        jButton5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selection.png"))); // NOI18N
        jButton5.setText("Lọc");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);

        jButton6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        jButton6.setText("Xuất ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);

        tblReceipt.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblReceipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReceiptMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblReceipt);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Phiếu nhập", new javax.swing.ImageIcon(getClass().getResource("/images/insurance.png")), jPanel32); // NOI18N

        jPanel24.setLayout(new java.awt.GridLayout(1, 0));

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        jLabel32.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel32.setText("Từ ngày");

        jLabel33.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel33.setText("Thể loại");

        txtFromDateProduct.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel34.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel34.setText("Đến ngày");

        txtEndDateProduct.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        cbbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hàng bán chạy", "Hàng tồn kho", " " }));
        cbbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFromDateProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(txtEndDateProduct, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbType, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFromDateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEndDateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel24.add(jPanel25);

        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder("Tổng hợp"));

        jLabel37.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel37.setText("Số lượng");

        txtQttyProduct.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtQttyProduct.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtDCashProduct.setFont(new java.awt.Font("Cambria", 1, 27)); // NOI18N
        txtDCashProduct.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel38.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel38.setText("Tổng tiền");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQttyProduct)
                    .addComponent(txtDCashProduct)))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQttyProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDCashProduct))
                .addContainerGap())
        );

        jPanel24.add(jPanel26);

        jButton7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);

        btnFillProduct.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnFillProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/selection.png"))); // NOI18N
        btnFillProduct.setText("Lọc");
        btnFillProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFillProductActionPerformed(evt);
            }
        });
        jPanel7.add(btnFillProduct);

        jButton9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        jButton9.setText("Xuất ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton9);

        tblProduct.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tblProduct);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane9))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sản phẩm", new javax.swing.ImageIcon(getClass().getResource("/images/box (1).png")), jPanel5); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Nhân viên");
    }// </editor-fold>//GEN-END:initComponents

    private void tblBillReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBillReportMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBillReportMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean checkEndate = txtFromDate.getText().isEmpty() & txtEnđate.getText().isEmpty();
        boolean checkStart = !txtFromDate.getText().isEmpty() & !txtEnđate.getText().isEmpty();
        if (checkEndate || checkStart) {
            initDataBillReport();
            return;
        }
        setErrorMsg("Bạn phải nhập cả 2 ngày, hoặc không");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        txtCodeBill.setText("");
        txtCusName.setText("");
        txtStaffName.setText("");
        txtFromDate.setText("");
        txtEnđate.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean checkEndate = txtFromDate.getText().isEmpty() & txtEnđate.getText().isEmpty();
        boolean checkStart = !txtFromDate.getText().isEmpty() & !txtEnđate.getText().isEmpty();
        if (checkEndate || checkStart) {
            WriteReportBill excelExample = new WriteReportBill();
            final List<ProcedureReportBill> books = billController.getReportBill(txtCodeBill.getText(), txtCusName.getText(), txtStaffName.getText(), txtFromDate.getText(), txtEnđate.getText());
            final String excelFilePath = "F:\\DHXD\\2021\\Doantotnghiep\\SourceCode\\StoreManager\\StoreManager\\src\\main\\resources\\file\\ReportBill";
            CodeSystem codeSystem = excelExample.writeExcel(books, excelFilePath);
            if (codeSystem.equals(CodeSystem.SUCCESS05)) {
                setSuccessMsg(codeSystem.getDescription());

            } else {
                setErrorMsg(codeSystem.getDescription());
            }
            return;
        }
        setErrorMsg("Bạn phải nhập cả 2 ngày, hoặc không");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtRecieptCode.setText("");
        txtDistributorName.setText("");
        txtStaffNameReceipt.setText("");
        txtFromDateReceipt.setText("");
        txtEndDateReceipt.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        boolean checkEndate = txtFromDateReceipt.getText().isEmpty() & txtEndDateReceipt.getText().isEmpty();
        boolean checkStart = !txtFromDateReceipt.getText().isEmpty() & !txtEndDateReceipt.getText().isEmpty();
        if (checkEndate || checkStart) {
            initDataReceipt();
            return;
        }
        setErrorMsg("Bạn phải nhập cả 2 ngày, hoặc không");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        boolean checkEndate = txtFromDateReceipt.getText().isEmpty() & txtEndDateReceipt.getText().isEmpty();
        boolean checkStart = !txtFromDateReceipt.getText().isEmpty() & !txtEndDateReceipt.getText().isEmpty();
        if (checkEndate || checkStart) {
            WriteReportReceipt excelExample = new WriteReportReceipt();
            final List<ProcedureReportBill> books = receiptController.getReportReceipt(txtRecieptCode.getText(), txtDistributorName.getText(), txtStaffNameReceipt.getText(), txtFromDateReceipt.getText(), txtEndDateReceipt.getText());
            final String excelFilePath = "F:\\DHXD\\2021\\Doantotnghiep\\SourceCode\\StoreManager\\StoreManager\\src\\main\\resources\\file\\ReportReceipt";
            CodeSystem codeSystem = excelExample.writeExcel(books, excelFilePath);
            if (codeSystem.equals(CodeSystem.SUCCESS05)) {
                setSuccessMsg(codeSystem.getDescription());

            } else {
                setErrorMsg(codeSystem.getDescription());
            }
            return;
        }
        setErrorMsg("Bạn phải nhập cả 2 ngày, hoặc không");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tblReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReceiptMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblReceiptMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        cbbType.setSelectedIndex(0);
        txtFromDateProduct.setText("");
        txtEndDateProduct.setText("");
        txtQttyProduct.setText("");
        txtDCashProduct.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnFillProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFillProductActionPerformed
        boolean checkEndate = txtFromDateProduct.getText().isEmpty() & txtEndDateProduct.getText().isEmpty();
        boolean checkStart = !txtFromDateProduct.getText().isEmpty() & !txtEndDateProduct.getText().isEmpty();
        if (checkEndate || checkStart) {

            if (cbbType.getSelectedIndex() != 0) {
                initDataProductInventory();
            } else {
                initDataProduct();
            }
            return;
        }
        setErrorMsg("Bạn phải nhập cả 2 ngày, hoặc không");
    }//GEN-LAST:event_btnFillProductActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        boolean checkEndate = txtFromDateProduct.getText().isEmpty() & txtEndDateProduct.getText().isEmpty();
        boolean checkStart = !txtFromDateProduct.getText().isEmpty() & !txtEndDateProduct.getText().isEmpty();
        if (checkEndate || checkStart) {

            CodeSystem codeSystem = null;
            if (cbbType.getSelectedIndex() != 0) {
                WriteReportProductInventory excelExample = new WriteReportProductInventory();
                final List<ProcedureReportProductInventory> books = productController.getReportProductInventory(txtFromDateProduct.getText(), txtEndDateProduct.getText());
                final String excelFilePath = "F:\\DHXD\\2021\\Doantotnghiep\\SourceCode\\StoreManager\\StoreManager\\src\\main\\resources\\file\\ReportProductInventory";
                codeSystem = excelExample.writeExcel(books, excelFilePath);
            } else {
                WriteReportProduct excelExample = new WriteReportProduct();
                final List<ProcedureReportProduct> books = productController.getReportProduct(txtFromDateProduct.getText(), txtEndDateProduct.getText());
                final String excelFilePath = "F:\\DHXD\\2021\\Doantotnghiep\\SourceCode\\StoreManager\\StoreManager\\src\\main\\resources\\file\\ReportProduct";
                codeSystem = excelExample.writeExcel(books, excelFilePath);
            }

            if (codeSystem.equals(CodeSystem.SUCCESS05)) {
                setSuccessMsg(codeSystem.getDescription());

            } else {
                setErrorMsg(codeSystem.getDescription());
            }
            return;
        }
        setErrorMsg("Bạn phải nhập cả 2 ngày, hoặc không");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductMouseClicked

    private void cbbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFillProduct;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblBillReport;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTable tblReceipt;
    private javax.swing.JTextField txtCodeBill;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtDCashBill;
    private javax.swing.JTextField txtDCashProduct;
    private javax.swing.JTextField txtDCashReceipt;
    private javax.swing.JTextField txtDistributorName;
    private javax.swing.JFormattedTextField txtEndDateProduct;
    private javax.swing.JFormattedTextField txtEndDateReceipt;
    private javax.swing.JFormattedTextField txtEnđate;
    private javax.swing.JFormattedTextField txtFromDate;
    private javax.swing.JFormattedTextField txtFromDateProduct;
    private javax.swing.JFormattedTextField txtFromDateReceipt;
    private javax.swing.JTextField txtQttyBill;
    private javax.swing.JTextField txtQttyBillReceipt;
    private javax.swing.JTextField txtQttyProduct;
    private javax.swing.JTextField txtRecieptCode;
    private javax.swing.JTextField txtStaffName;
    private javax.swing.JTextField txtStaffNameReceipt;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initData() {
        initDataBillReport();
        initDataReceipt();
        initDataProduct();
    }

    private void initDataBillReport() {
        customerResponses = billController.getReportBillObject(txtCodeBill.getText(), txtCusName.getText(), txtStaffName.getText(), txtFromDate.getText(), txtEnđate.getText());
        Object[] obj = new Object[]{"Mã hóa đơn", "Mã khách hàng", "Tên khách hàng", "Thời gian", "Tổng tiền", "Tên nhân viên", "Mô tả"};
        tableModel = new DefaultTableModel(obj, 0);
        tableRowSorter = new TableRowSorter<>(tableModel);
        tblBillReport.setModel(tableModel);
        tblBillReport.setRowSorter(tableRowSorter);
        count = 0;
        tableModel.setRowCount(0);
        try {
            customerResponses.forEach((Object[] item) -> {
                tableModel.addRow(item);

            });
        } catch (Exception exception) {
            log.error("Can't add row to table model ");
            exception.printStackTrace();

        }
        txtQttyBill.setText(billController.getReportBillQtty(txtCodeBill.getText(), txtCusName.getText(), txtStaffName.getText(), txtFromDate.getText(), txtEnđate.getText()));
        txtDCashBill.setText(billController.getReportBillSum(txtCodeBill.getText(), txtCusName.getText(), txtStaffName.getText(), txtFromDate.getText(), txtEnđate.getText()));
    }

    private void initDataReceipt() {
        customerResponsesReceipt = receiptController.getReportReceiptObject(txtRecieptCode.getText(), txtDistributorName.getText(), txtStaffNameReceipt.getText(), txtFromDateReceipt.getText(), txtEndDateReceipt.getText());
        Object[] obj = new Object[]{"Mã phiếu nhập", "Mã nhà phân phối", "Tên nhà phân phối", "Thời gian", "Tổng tiền", "Tên nhân viên", "Mô tả"};
        tableModelReceipt = new DefaultTableModel(obj, 0);
        tableRowSorterProductTypeReceipt = new TableRowSorter<>(tableModelReceipt);
        tblReceipt.setModel(tableModelReceipt);
        tblReceipt.setRowSorter(tableRowSorterProductTypeReceipt);
        tableModelReceipt.setRowCount(0);
        try {
            customerResponsesReceipt.forEach((Object[] item) -> {
                tableModelReceipt.addRow(item);
            });
        } catch (Exception exception) {
            log.error("Can't add row to table model ");
            exception.printStackTrace();

        }
        txtQttyBillReceipt.setText(receiptController.getReportReceiptQtty(txtRecieptCode.getText(), txtDistributorName.getText(), txtStaffNameReceipt.getText(), txtFromDateReceipt.getText(), txtEndDateReceipt.getText()));
        txtDCashReceipt.setText(receiptController.getReportReceiptSum(txtRecieptCode.getText(), txtDistributorName.getText(), txtStaffNameReceipt.getText(), txtFromDateReceipt.getText(), txtEndDateReceipt.getText()));
    }

    private void initDataProduct() {
        customerResponsesProduct = productController.getReportProductObject(txtFromDateProduct.getText(), txtEndDateProduct.getText());
        Object[] obj = new Object[]{"Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Tổng tiền"};
        tableModelProduct = new DefaultTableModel(obj, 0);
        tblProduct.setModel(tableModelProduct);
        tableModelProduct.setRowCount(0);
        BigDecimal quantity = new BigDecimal(BigInteger.ZERO);
        BigDecimal dcash = new BigDecimal(BigInteger.ZERO);
        for (Iterator<Object[]> iterator = customerResponsesProduct.iterator(); iterator.hasNext();) {
            Object[] next = iterator.next();
            quantity = quantity.add((BigDecimal) next[2]);
            dcash = dcash.add((BigDecimal) next[3]);
            next[3] = String.format("%,.0f", next[3]);
            tableModelProduct.addRow(next);

        }
        txtQttyProduct.setText(String.valueOf(quantity));
        txtDCashProduct.setText(String.format("%,.0f", dcash));
    }

    private void initDataProductInventory() {
        customerResponsesProduct = productController.getReportProductInventoryObject(txtFromDateProduct.getText(), txtEndDateProduct.getText());
        Object[] obj = new Object[]{"Mã sản phẩm", "Tên sản phẩm", "Giá nhập", "Số lượng", "Tổng tiền"};
        tableModelProductInventory = new DefaultTableModel(obj, 0);
        tblProduct.setModel(tableModelProductInventory);
        tableModelProductInventory.setRowCount(0);
        Integer quantity = 0;
        BigDecimal dcash = new BigDecimal(BigInteger.ZERO);
        for (Iterator<Object[]> iterator = customerResponsesProduct.iterator(); iterator.hasNext();) {
            Object[] next = iterator.next();
            quantity = (Integer) next[3];
            dcash = dcash.add((BigDecimal) next[4]);
            next[4] = String.format("%,.0f", next[4]);
            next[2] = String.format("%,.0f", next[2]);
            tableModelProductInventory.addRow(next);
        }

        txtQttyProduct.setText(String.valueOf(quantity));
        txtDCashProduct.setText(String.format("%,.0f", dcash));
    }

}
